jobs:
  build:
    runs-on: 'windows-latest'
    steps:
      - uses: 'actions/checkout@v5'
      - name: 'Install Poetry'
        run: 'pipx install poetry yq'
      - name: 'Set up Python'
        uses: 'actions/setup-python@v6'
        with:
          cache: 'poetry'
          python-version: '3.13'
      - name: 'Install dependencies (Poetry)'
        run: |
          poetry install
          poetry run -- pip install pyinstaller
        shell: 'bash'
      - name: 'Build with PyInstaller'
        run: |
          vers=$(echo "$(tomlq -r '.project.version|split(".")|map(tonumber)|@csv' pyproject.toml),0")
          version=$(tomlq -r .project.version pyproject.toml)
          project_name=$(tomlq -r '.project.urls.repository|split("/")[-1]' pyproject.toml)
          while IFS=$' ' read -r script_name python_path func_name; do
            func_name="${func_name#"${func_name%%[![:space:]]*}"}"
            func_name="${func_name%"${func_name##*[![:space:]]}"}"
            cat > temp_script.py <<EOF
          from ${python_path} import ${func_name}
          if __name__ == '__main__':
              ${func_name}()
          EOF
            cat temp_script.py
            cat > version-info.txt <<EOF
          VSVersionInfo(
              ffi=FixedFileInfo(date=(0, 0),
                                filevers=(${vers}),
                                OS=0x4,
                                fileType=0x1,
                                flags=0x0,
                                mask=0x3f,
                                prodvers=(${vers}),
                                subtype=0x0),
              kids=[
                  StringFileInfo([
                      StringTable(u'040904B0', [
                          StringStruct(u'CompanyName', u'Tatsh'),
                          StringStruct(
                              u'FileDescription',
                              u'${script_name} from ${project_name}. - ${{github.server_url}}/${{github.repository}}'
                          ),
                          StringStruct(u'FileVersion', u'${version}'),
                          StringStruct(u'InternalName', u'${script_name}.exe'),
                          StringStruct(u'LegalCopyright', u'Copyright (c) ${project_name} authors.'),
                          StringStruct(u'OriginalFilename', u'${script_name}.exe'),
                          StringStruct(u'ProductName', u'${project_name}'),
                          StringStruct(u'ProductVersion', u'${version}')
                      ])
                  ]),
                  VarFileInfo([VarStruct(u'Translation', [0x409, 1200, 0x809, 1252])])
              ])
          EOF
            cat version-info.txt
            poetry run -- pyinstaller --onefile -n "${script_name}" \
              --hidden-import colorlog -y --version-file version-info.txt temp_script.py
            cat "${script_name}.spec"
          done < <(tomlq -r '.project.scripts|to_entries[]|"\(.key) \(.value|split(":")|join(" "))"' pyproject.toml)
        shell: 'bash'
      - name: 'Upload Artifacts'
        uses: 'actions/upload-artifact@v4'
        with:
          name: 'pyinstaller-binaries'
          path: |
            dist/*.exe
name: 'PyInstaller'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
